Description: Gytis / Challenge 3

Parameters:

  EnvironmentName:
    Description: Environment Name
    Type: String

  NetworkEnvironmentName:
    Description: Network Infrastructure Environment Name
    Type: String

  AMIId:
    Description: AMI for EC2 Instance
    Type: String

Resources:

  RoleForSSMAccess:
    Type: AWS::IAM::Role
    Properties:
      Description: Allow EC2 Session Manager to access Server
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref RoleForSSMAccess

  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web Access Security Group
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkEnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  ServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AMIId
      IamInstanceProfile: !Ref ServerInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet: 
            - !Ref WebAccessSecurityGroup
          SubnetId:
            Fn::ImportValue:
              !Sub "${NetworkEnvironmentName}-PRIV-NET"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
